version: '3'

services:
  frontend:
    build: ./client
    container_name: react-ui
    ports:
      - "3000:4000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    networks:
      - chat-network

  backend:
    build: ./chat-server
    container_name: chat-server
    ports:
      - "6000:6000"
networks:
  chat-network:
    driver: bridge
